repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
        always_run: true
      - id: poetry-export
        always_run: true
        args:
          - "--without-hashes"
          - "-f"
          - "requirements.txt"
          - "-o"
          - "requirements.txt"