repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: poetry-export
        name: poetry-export
        language: system
        entry: bash scripts/poetry_export.sh
        always_run: true
      - id: flet-pack
        name: flet-pack
        language: system
        entry: bash -x scripts/flet_pack.sh